/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaffPerformanceRouteImport } from './routes/staff-performance'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CountryPerformanceRouteImport } from './routes/country-performance'
import { Route as ChannelPerformanceRouteImport } from './routes/channel-performance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const StaffPerformanceRoute = StaffPerformanceRouteImport.update({
  id: '/staff-performance',
  path: '/staff-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryPerformanceRoute = CountryPerformanceRouteImport.update({
  id: '/country-performance',
  path: '/country-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelPerformanceRoute = ChannelPerformanceRouteImport.update({
  id: '/channel-performance',
  path: '/channel-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/channel-performance': typeof ChannelPerformanceRoute
  '/country-performance': typeof CountryPerformanceRoute
  '/customers': typeof CustomersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff-performance': typeof StaffPerformanceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/channel-performance': typeof ChannelPerformanceRoute
  '/country-performance': typeof CountryPerformanceRoute
  '/customers': typeof CustomersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff-performance': typeof StaffPerformanceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/channel-performance': typeof ChannelPerformanceRoute
  '/country-performance': typeof CountryPerformanceRoute
  '/customers': typeof CustomersRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/staff-performance': typeof StaffPerformanceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/channel-performance'
    | '/country-performance'
    | '/customers'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/staff-performance'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/channel-performance'
    | '/country-performance'
    | '/customers'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/staff-performance'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/channel-performance'
    | '/country-performance'
    | '/customers'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/staff-performance'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChannelPerformanceRoute: typeof ChannelPerformanceRoute
  CountryPerformanceRoute: typeof CountryPerformanceRoute
  CustomersRoute: typeof CustomersRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  StaffPerformanceRoute: typeof StaffPerformanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/staff-performance': {
      id: '/staff-performance'
      path: '/staff-performance'
      fullPath: '/staff-performance'
      preLoaderRoute: typeof StaffPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/country-performance': {
      id: '/country-performance'
      path: '/country-performance'
      fullPath: '/country-performance'
      preLoaderRoute: typeof CountryPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-performance': {
      id: '/channel-performance'
      path: '/channel-performance'
      fullPath: '/channel-performance'
      preLoaderRoute: typeof ChannelPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChannelPerformanceRoute: ChannelPerformanceRoute,
  CountryPerformanceRoute: CountryPerformanceRoute,
  CustomersRoute: CustomersRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  StaffPerformanceRoute: StaffPerformanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
