/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as SlaRouteImport } from './routes/sla'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ChannelPerformanceRouteImport } from './routes/channel-performance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCallLogRouteImport } from './routes/api/public/call-log'

const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sms.lazy').then((d) => d.Route))
const SlaRoute = SlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/customers.lazy').then((d) => d.Route))
const ChannelPerformanceRoute = ChannelPerformanceRouteImport.update({
  id: '/channel-performance',
  path: '/channel-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCallLogRoute = ApiPublicCallLogRouteImport.update({
  id: '/api/public/call-log',
  path: '/api/public/call-log',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/channel-performance': typeof ChannelPerformanceRoute
  '/customers': typeof CustomersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sla': typeof SlaRoute
  '/sms': typeof SmsRoute
  '/api/public/call-log': typeof ApiPublicCallLogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/channel-performance': typeof ChannelPerformanceRoute
  '/customers': typeof CustomersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sla': typeof SlaRoute
  '/sms': typeof SmsRoute
  '/api/public/call-log': typeof ApiPublicCallLogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/channel-performance': typeof ChannelPerformanceRoute
  '/customers': typeof CustomersRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sla': typeof SlaRoute
  '/sms': typeof SmsRoute
  '/api/public/call-log': typeof ApiPublicCallLogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attendance'
    | '/auth'
    | '/channel-performance'
    | '/customers'
    | '/reset-password'
    | '/settings'
    | '/sla'
    | '/sms'
    | '/api/public/call-log'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendance'
    | '/auth'
    | '/channel-performance'
    | '/customers'
    | '/reset-password'
    | '/settings'
    | '/sla'
    | '/sms'
    | '/api/public/call-log'
  id:
    | '__root__'
    | '/'
    | '/attendance'
    | '/auth'
    | '/channel-performance'
    | '/customers'
    | '/reset-password'
    | '/settings'
    | '/sla'
    | '/sms'
    | '/api/public/call-log'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  ChannelPerformanceRoute: typeof ChannelPerformanceRoute
  CustomersRoute: typeof CustomersRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SlaRoute: typeof SlaRoute
  SmsRoute: typeof SmsRoute
  ApiPublicCallLogRoute: typeof ApiPublicCallLogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sla': {
      id: '/sla'
      path: '/sla'
      fullPath: '/sla'
      preLoaderRoute: typeof SlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channel-performance': {
      id: '/channel-performance'
      path: '/channel-performance'
      fullPath: '/channel-performance'
      preLoaderRoute: typeof ChannelPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/call-log': {
      id: '/api/public/call-log'
      path: '/api/public/call-log'
      fullPath: '/api/public/call-log'
      preLoaderRoute: typeof ApiPublicCallLogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  ChannelPerformanceRoute: ChannelPerformanceRoute,
  CustomersRoute: CustomersRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SlaRoute: SlaRoute,
  SmsRoute: SmsRoute,
  ApiPublicCallLogRoute: ApiPublicCallLogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
