INSERT INTO public.countries (code, name_ko, name_en, is_active) VALUES
('MY','말레이시아','Malaysia',true),
('ID','인도네시아','Indonesia',true),
('SG','싱가포르','Singapore',true),
('LA','라오스','Laos',true),
('JP','일본','Japan',true),
('TW','대만','Taiwan',true),
('HK','홍콩','Hong Kong',true),
('TL','동티모르','Timor-Leste',true),
('BT','부탄','Bhutan',true),
('MV','몰디브','Maldives',true),
('AF','아프가니스탄','Afghanistan',true),
('IR','이란','Iran',true),
('IQ','이라크','Iraq',true),
('TR','튀르키예','Turkey',true),
('SY','시리아','Syria',true),
('SA','사우디아라비아','Saudi Arabia',true),
('AE','아랍에미리트','UAE',true),
('NG','나이지리아','Nigeria',true),
('KE','케냐','Kenya',true),
('ET','에티오피아','Ethiopia',true),
('UG','우간다','Uganda',true),
('TZ','탄자니아','Tanzania',true),
('ZA','남아프리카공화국','South Africa',true),
('MA','모로코','Morocco',true),
('DZ','알제리','Algeria',true),
('SD','수단','Sudan',true),
('BR','브라질','Brazil',true),
('PE','페루','Peru',true),
('MX','멕시코','Mexico',true),
('CO','콜롬비아','Colombia',true),
('AR','아르헨티나','Argentina',true),
('AU','호주','Australia',true),
('NZ','뉴질랜드','New Zealand',true),
('FR','프랑스','France',true),
('DE','독일','Germany',true),
('IT','이탈리아','Italy',true),
('ES','스페인','Spain',true),
('PL','폴란드','Poland',true),
('NL','네덜란드','Netherlands',true),
('KR','대한민국','South Korea',true),
('FJ','피지','Fiji',true),
('PG','파푸아뉴기니','Papua New Guinea',true)
ON CONFLICT (code) DO NOTHING;